name: Pull request checks
on:
    push:
        branches: ['master']
    pull_request:
        branches: ['master']
jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: 'npm'

            - run: npm ci

            - name: Check code style
              run: |
                  npx prettier --check .

            - name: Run eslint
              run: |
                  npx eslint .
